apiVersion: v1
kind: Service
metadata:
  name: PROJECTNAME-service
spec:
  selector:
    app: PROJECTNAME
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: PROJECTNAME
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: PROJECTNAME
    spec:
      containers:
      - name: PROJECTNAME
        image: PROJECTNAME:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
